### ISSUE TITLE
Importing Database-Dump in MySQL/MariaDB leads to errors

### ISSUE THREAD

**Issue by alexgit2k** [craftcms/europa-museum#10]
### Description

Demo-website should work with "PostgreSQL (11.5+) / MySQL (5.7+)", however importing the database-dump leads to errors.

### Steps to reproduce

1. mysql craftcms  < seed.sql
`ERROR 1193 (HY000) at line 8: Unknown system variable 'statement_timeout'`

### Additional info

- Craft version: 3
- PHP version: -
- Database driver & version: MariaDB 10.6
- Plugins & versions:

**Comment by mattstein** [comment]
Fixed that line in the readme since it was misleadingly describing Craft’s database requirements and not the project’s. _Local Development Setup_ step 2 is more specific/accurate:

> Make sure you’ve used nitro db new to create a PostgreSQL 13 database engine.

Thanks for pointing this out!
